### ISSUE TITLE
Update Metadata fields

### ISSUE THREAD

**Issue by 6fears7** [bck01215/kube-logs-generator#2]
https://github.com/bck01215/kube-logs-generator/blob/33a05060a2a65e8337bdc4f9542475d33892464b/src/main.rs#L105

AppDev requests having the following metadata pulled:

- kube.pod.uid
- container.id
- hostname, if possible

to enable log stream viewing by those fields in Elastic's APM

**Comment by bck01215** [comment]
You appear to be lost sir. 

Perhaps a repo in your team's private instance would be open to supporting this

https://gitlab.occ.liberty.edu/obs/okd-to-kafka
